# removed the -c option because we need to link this
QuipuServer:
	gcc -shared -Wall -Werror -I/usr/lib/jvm/java-8-oracle/include -I/usr/lib/jvm/java-8-oracle/include/linux/ -o ../target/libQuipuServer.so -fPIC QuipuServer.c
clean:
	rm -f *.o 
