# removed the -c option because we need to link this
HelloWorld:
	gcc -shared -Wall -Werror -I/usr/lib/jvm/java-8-oracle/include -I/usr/lib/jvm/java-8-oracle/include/linux/ -o libHelloWorld.so -fPIC HelloWorld.c
clean:
	rm -f *.o 
