/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloWorld */

#ifndef _Included_QuipuServer
#define _Included_QuipuServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     QuipuServer
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mmmsys_spider_QuipuServer_print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}

//char *allocate_strmem (int);
//uint8_t *allocate_ustrmem (int);
//int send_gatewayarp_request(char*, char*, char*);

#endif
#endif
